In [30]:
import torch

In [31]:
n = 5

In [32]:
A = torch.rand((n,n))*10

In [33]:
A=A+A.T

In [34]:
A[torch.arange(n),torch.arange(n)]=0

In [35]:
A.float()

tensor([[ 0.0000,  9.2812, 14.7479, 14.4243,  4.6083],
        [ 9.2812,  0.0000,  4.1306, 12.3265, 16.4985],
        [14.7479,  4.1306,  0.0000,  8.0229, 13.8094],
        [14.4243, 12.3265,  8.0229,  0.0000, 14.9730],
        [ 4.6083, 16.4985, 13.8094, 14.9730,  0.0000]])

In [36]:
xy = torch.rand((n,2),requires_grad=True)

In [37]:
xy

tensor([[0.4725, 0.1732],
        [0.2452, 0.8628],
        [0.3467, 0.0421],
        [0.6696, 0.9651],
        [0.1882, 0.6927]], requires_grad=True)

In [38]:
optimizer = torch.optim.Adam([xy])

In [39]:
def get_loss():
    loss = 0.
    for i in range(n):
        for j in range(i+1,n):
            loss += torch.abs(torch.sum((xy[i]-xy[j])**2)-A[i,j]**2)
    return loss

In [40]:
for epoch in range(10000):
    optimizer.zero_grad()
    loss = get_loss()
    loss.backward()
    optimizer.step()

In [41]:
i = 2
j = 3

In [42]:
torch.abs(torch.sum((xy[i]-xy[j])**2)-A[i,j]**2)

tensor(0.0111, grad_fn=<AbsBackward>)

In [43]:
get_loss()

tensor(191.2896, grad_fn=<AddBackward0>)

In [44]:
print(xy)

tensor([[ 2.0517, -6.0886],
        [-6.6879, -0.5090],
        [-4.2516,  3.1819],
        [ 1.8986,  8.3350],
        [ 6.6548, -5.8620]], requires_grad=True)
