In [1]:
import torch

In [2]:
n = 5

In [3]:
A = torch.rand((n,n))*10

In [4]:
A=A+A.T

AttributeError: 'Tensor' object has no attribute 'T'

In [5]:
A[torch.arange(n),torch.arange(n)]=0

In [6]:
A.float()

tensor([[0.0000, 2.4306, 0.8980, 8.0278, 7.2840],
        [0.6403, 0.0000, 8.8879, 5.4783, 6.2031],
        [6.4395, 1.1408, 0.0000, 5.8878, 4.4346],
        [5.3918, 9.3330, 3.3241, 0.0000, 0.8291],
        [4.1699, 7.3322, 1.0321, 5.0027, 0.0000]])

In [7]:
xy = torch.rand((n,2),requires_grad=True)

In [8]:
xy

tensor([[0.8952, 0.4316],
        [0.1524, 0.5238],
        [0.1500, 0.9777],
        [0.8731, 0.8342],
        [0.5802, 0.9505]], requires_grad=True)

In [9]:
optimizer = torch.optim.Adam([xy])

In [10]:
def get_loss():
    loss = 0.
    for i in range(n):
        for j in range(i+1,n):
            loss += torch.abs(torch.sum((xy[i]-xy[j])**2)-A[i,j]**2)
    return loss

In [11]:
for epoch in range(10000):
    optimizer.zero_grad()
    loss = get_loss()
    loss.backward()
    optimizer.step()

In [12]:
i = 2
j = 3

In [13]:
torch.abs(torch.sum((xy[i]-xy[j])**2)-A[i,j]**2)

tensor(0.0145, grad_fn=<AbsBackward>)

In [14]:
get_loss()

tensor(74.3729, grad_fn=<AddBackward0>)

In [15]:
print(xy)

tensor([[-2.2266, -2.6422],
        [-3.1224,  2.8706],
        [ 2.7439, -2.0548],
        [ 2.3194,  3.8190],
        [ 3.0606,  2.3685]], requires_grad=True)
